### ISSUE TITLE
Поиск во вложенных папках и маски

### ISSUE THREAD

**Issue by Koboku** [kelciour/playphrase#1]
Как  сделать так, чтобы искало сразу в нескольких директориях (например во всех 10 папках с друзьями), или во вложенных папках? 

Можно ли как-то прописать в скрипте, чтобы он искал по маскам .eng, например friends_s1.12.eng, а оригинальное название видео оставалось friends_s1.12?

Я в этом совершенно не разбираюсь, сам скрипт очень понравился :)

**Comment by kelciour** [comment]
Скрипт ищет рекурсивно. Просто укажите корневую папку и заново выполните команду `_init_`, чтобы сгенерировать .txt файлы по всем найденным .srt файлам, по которым уже и будет происходить поиск с помощью grep.

Так, с ходу, можно, например, изменить строчку [#L360](https://github.com/kelciour/playphrase/blob/master/playphrase.py#L360) с `movie_filename = filename + "." + ext` на `movie_filename = filename.rstrip(".eng") + "." + ext`
Таким образом скрипт будет предполагать, что в имени видеофайла отсутствует суффикс ".eng".

**Comment by kelciour** [comment]
На всякий случай добавил исправленный бинарник под Windows.
[playphrase-issue_1.zip](https://github.com/kelciour/playphrase/files/1950968/playphrase-issue_1.zip)

**Comment by Koboku** [comment]
Спс, нам гуманитариям такие вещи тяжело даются)
