### ISSUE TITLE
How to fix Native language?

### ISSUE THREAD

**Issue by raj6996** [kelciour/playphrase#10]
I saw you used your native russian language,  when I used my own language it shows only ?????
how to fix it. thanks.

**Comment by kelciour** [comment]
You're on Windows 10?

**Comment by raj6996** [comment]
Yes sir!

**Comment by kelciour** [comment]
Try to specify "Lucida Console" as the console font in cmd settings - https://superuser.com/a/1305445

Otherwise, instead of cmd, install Windows Terminal - https://devblogs.microsoft.com/commandline/introducing-windows-terminal/

Maybe you'd need to enable UTF-8, but it might work without it - https://akr.am/blog/posts/using-utf-8-in-the-windows-terminal

**Comment by raj6996** [comment]
I have followed all your guidance, nothing works except Windows Teminal!
but it has still bug issue.
`D:\0.Github\playphrase-win64>playphrase -i "D:\0.Github\playphrase\English" -vs "नमस्ते"`
but shows in Windows teminal>
https://ibb.co/S0d0j88
it shows space?
Original CMD:  only Rectangle instead of  "नमस्ते"
I googled last 2 days, no proper or satisfied result, but found this, though it remain same problem.
Here is problem: only long space after "नमस्ते      "
https://ibb.co/Cn1x9tc
I will post this issue on that console page. Hope they will answer me.
https://github.com/cbucher/console/issues/453

**Comment by kelciour** [comment]
In this case, without spending more time on googling, I'd suggest to install Git for Windows - https://git-scm.com/download/win

It includes Git Bash Here command in the context menu that will open a new console window in the current folder and playphrase can be run with `./playphrase`, i.e.

> ./playphrase -i "G:\English Movies" नमस्ते

And if the search string contains any spaces, wrap it with double quotes, i.e.

> ./playphrase -i "G:\English Movies" "नमस्ते नमस्ते"

**Comment by raj6996** [comment]
I installed many terminal including gitbash, but hindi words not works except Console Terminal
https://github.com/cbucher/console
Have you tested hindi words "नमस्ते" inside Gitbash. Paste, it not showing.
can you tell me step by step how to run properly, if possible short youtube tutorials welcome.
![gitbash hindi error](https://user-images.githubusercontent.com/16426916/95369679-5e7a1180-08f5-11eb-875a-c1a69bb04933.jpg)
P.S. I used many Terminals but none of works properly with Hindi text. so It was complex to find Hindi text from rendered text from playphrase script.
only English works.

**Comment by kelciour** [comment]
I think it's telling the truth and ./playphrase is a directory.

Use `cd playphrase` to change the current directory before running the command and make sure that playphrase.exe can be found in the current folder, e.g. by using `ls` to get a list of files in the current folder. 

I guess, the command was a bit confusing. Use this command instead,

> ./playphrase.exe -i "G:\English Movies" "नमस्ते नमस्ते"

**Comment by raj6996** [comment]
Finally works...Thanks for great help!
