### ISSUE TITLE
(Tuts) ripgrep usage in playphrase

### ISSUE THREAD

**Issue by raj6996** [kelciour/playphrase#12]
I watched ripgrep basics on youtube as well github page and google. But I can't figure out how to use here?
if you have some time make some youtube tutorials how to use ripgrep inside playphrase?
Thanks.

**Comment by kelciour** [comment]
It's just grep replacement and it's not exposed to the user. I can only suggest to look up some basic tutorial on regular expressions like `\b` for word boundary and something similar. For some reason, grep produced incorrect results with `\b` and some russian text, but ripgrep worked correctly.
