### ISSUE TITLE
(Feature) Option to setup Audio Language

### ISSUE THREAD

**Issue by raj6996** [kelciour/playphrase#13]
First of all thanks for updating Python v3 and fixing other issues so fast.
I used dual audio films, output file of  Sam's videogrep was my Native language instead of English.
Here I have tested your scripts video segments were English only.
Is there anyway to setup audio of dual voiced films?
Thanks.

**Comment by kelciour** [comment]
The script used the first audio stream by default. I updated the script and now the video segment should contain the same number of audio tracks as in the video file, i.e. you should be able to change them with your video player.

Aside from that, I can only recommend to use MKVToolNix GUI either to remove any extra audio tracks or change their order.

Additionally, mpv.conf can be updated to allow mpv to automatically select a different audio track while playing the audio file.

https://mpv.io/manual/master/#options-alang

The option to setup the preferred audio language would be nice, if the video file contains multiple audio tracks, but it's not something I can do.
