### ISSUE TITLE
search only few words instead of long or full srt. segments!

### ISSUE THREAD

**Issue by raj6996** [kelciour/playphrase#15]
`(00:24:05,880, 00:24:32,040)	शास्त्री जी सच्चे गांधीवादी थे जिन्होंने अपना सारा जीवन सादगी से बिताया और उसे गरीबों की सेवा में लगाया। भारतीय स्वाधीनता संग्राम के सभी महत्वपूर्ण कार्यक्रमों व आंदोलनों में उनकी सक्रिय भागीदारी रही और उसके परिणामस्वरूप उन्हें कई बार जेलों में भी रहना पड़ा। स्वाधीनता संग्राम के जिन आंदोलनों में उनकी महत्वपूर्ण भूमिका रही उनमें 1921 का असहयोग आंदोलन, 1930 का दांडी मार्च तथा 1942 का भारत छोड़ो आंदोलन उल्लेखनीय हैं।`
Hindi srt like it....
Somedays ago I found bug.
When I searched भूमिका, upper mentioned srt segments omitted, Total result found 7.
but when I search using "भूमि", it could search. now it included भूमिका with 10,
You don't believe it. cause I searched basic regex code it still missing, may be i am beginner, so it can be my fault.
Real issue!
I used Videogrep to compare.
Videogrep only cut 
`स्वाधीनता संग्राम के जिन आंदोलनों में उनकी महत्वपूर्ण भूमिका रही उनमें 1921 का असहयोग आंदोलन, 1930 का दांडी मार्च तथा 1942 का भारत छोड़ो आंदोलन उल्लेखनीय हैं।`
Playphrase did whole paragraph cut, i.e.
`शास्त्री जी सच्चे गांधीवादी थे जिन्होंने अपना सारा जीवन सादगी से बिताया और उसे गरीबों की सेवा में लगाया। भारतीय स्वाधीनता संग्राम के सभी महत्वपूर्ण कार्यक्रमों व आंदोलनों में उनकी सक्रिय भागीदारी रही और उसके परिणामस्वरूप उन्हें कई बार जेलों में भी रहना पड़ा। स्वाधीनता संग्राम के जिन आंदोलनों में उनकी महत्वपूर्ण भूमिका रही उनमें 1921 का असहयोग आंदोलन, 1930 का दांडी मार्च तथा 1942 का भारत छोड़ो आंदोलन उल्लेखनीय हैं।`
how can I set like small sentence instead of whole paragraph.
Thanks.

**Comment by kelciour** [comment]
The script tries to join a few subtitles to a full sentence while generating txt files, but it's pretty simple and I could only test it with English.

Try to use `_init_` with `-limit 0` to skip this step, i.e.

    playphrase.exe -i "G:\English Movies" --limit 0 _init_
