### ISSUE TITLE
English subtitle create with Hindi srt/text(Generated with playprase)

### ISSUE THREAD

**Issue by raj6996** [kelciour/playphrase#16]
i have idea, I have two subtitles English text and Hindi TEXT(which I generated with playprase _init_). I made fragments separately both Hindi and English.
When I made with Hindi srt it create 92 parts, but while English srt only 65 parts.
I wanted to use with Hindi srt but subtitle in English. Is it possible?

**Comment by kelciour** [comment]
Not possible.

Maybe it could be done by writing some code to align English and Hindi subtitles but it's not something I can do.

Theoretically, it might work to copy Hindi subtitles to the media folder, use _init_ to generate txt files, replace Hindi subtitles with English subtitles, and generate video fragments. Or maybe it won't work.
