### ISSUE TITLE
Extract only one word!

### ISSUE THREAD

**Issue by raj6996** [kelciour/playphrase#17]
I checked additional option. I can't figured out. How do cut only one word instead of phrase?

**Comment by kelciour** [comment]
There's no such option. The script just uses timings from subtitles.

Another program is required to generate word-by-word subtitles. Something like https://github.com/lowerquality/gentle or https://github.com/saurabhshri/CCAligner or maybe https://github.com/readbeyond/aeneas

I haven't used aeneas for word-by-word alignment, CCAligner seems to be quite difficult to install and I only tried gentle a few years ago and don't know if there's another way to do something similar.

Gentle might skip some words but overall seems to work wery well. But it's quite slow and it might take a few minutes to sync one-minute audio file. I've attached a zip archive with a few sample files and `gentle.py` to convert json to srt - [gentle-sample.zip](https://github.com/kelciour/playphrase/files/5409545/gentle-sample.zip)

There's also DeepSpeech by Mozilla and DSAlign that might do word alignment but I don't know if it's easy to use or not.

- https://github.com/mozilla/DeepSpeech
- https://github.com/mozilla/DSAlign

Or maybe CMU Pocketsphinx and https://github.com/antiboredom/audiogrep

**Comment by raj6996** [comment]
Thanks I will try your guide.
