### ISSUE TITLE
Random order fixed from mass videos!

### ISSUE THREAD

**Issue by raj6996** [kelciour/playphrase#18]
One weird issue found! 
When I search any word in all web series or films series, it did not extract sequence way. I don't use random option, but it automatically randomize series. I checked Episode 01 extracted to last parts, and last episode extracted first.
Can you take a look into it. thanks.

**Comment by kelciour** [comment]
It should be fixed in https://github.com/kelciour/playphrase/releases/tag/v1.2.9
