### ISSUE TITLE
merge srt and mp4 with one file!

### ISSUE THREAD

**Issue by raj6996** [kelciour/playphrase#19]
Ok, I googeled but still no proper result.
I used your tools over videogrep as you have only subtitle with hardcode and softcode option.
I tried ffmpeg to join subtitle and sync with joined video but video don't show properly, is there any tools to fix it to merge all srt and mp4 files.
P.S. I don't used Hardcode subtiles, cause non-english srt not show properly. so I use -v -s option.

**Comment by kelciour** [comment]
Something like this should work and subtitles will be softsub.

> ffmpeg -i infile.mp4 -i infile.srt -c copy -c:s mov_text outfile.mp4
