### ISSUE TITLE
Cut

### ISSUE THREAD

**Issue by ghost** [kelciour/playphrase#2]
Thanks for your Help,All issue are Resolved and you can use update sub-cut.lua

**Comment by kelciour** [comment]
Thank you. That's great to know that it's useful.

I've updated `sub-cut.lua` script to fix this issue. Please replace your version (`cut.lua` or `sub-cut.lua`) with the updated version (`sub-cut.lua`) from [mpv-scripts](https://github.com/kelciour/mpv-scripts) repository.

And if I'm right, it seems that you're maybe talking about old version of the script (`cut.lua`) that is packaged by default with Windows build of playphrase. If this is the case, there were added a couple of new shortcuts and default shortcuts were changed to `ctrl+x`, 'ctrl+z', 'ctrl+c' in the newer version.

**Comment by KingslyEn** [comment]
Thanks you a lot,can I have your Email Adress or Instagram or ... Thanks a lot :+1: :1st_place_medal: 

And I have another question :) is there a way to gives us .srt files too?
one of Iranian Guy do this,Its use ffmpeg but with a GUI .exe
is it possible to add a script that gives us .srt with that timepoint
For Example start point is 00:01:00.000 and endpoint is 00:01:56.596
when we encode .mp4 we can encode .srt too, Not Hardsub

Again thank you a lot

**Comment by KingslyEn** [comment]
But I find a new issue, The codec is wrong,I have K-lite Media codec pack & HalliMedia spliter.
The .mp4 is play with MPC_HC,PotPlayer,KMPlayer and some other that use codec
But windows Media player cant open this encoding file,So as you know some of edditing video program cant open this too,
I re encode it with ffmpeg,with this code in cmd:
`ffmpeg -i input.mp4 -c:v libx264 -crf 18 -preset slow -c:a copy `output.mp4``
and the output.mp4 is correct and play in windows media player and all of video edditing program!
If it possible change the encode type.

**Comment by raj6996** [comment]
How did you edit subtitle with ffmpeg?
really interesting.
as videogrep was not works on windows I tired to use.
but Here works but no editing option.

**Comment by kelciour** [comment]
@KingslyEn 

> can I have your Email Adress

It's my nickname + @gmail.com, i.e. kelciour [at] gmail (dot) com.

> But windows Media player cant open this encoding file and just show black space with sound

Interesting. In the newer version I switched to mpv to do most of the encoding and the issue with Windows Media Player can be fixed by setting x264 profile level to 4.1, but for unknown reasons mpv mixes up video and audio streams and puts audio stream as the first stream in the file instead of video stream and some video editing software may not open correctly that file. For that reason, I reverted back to ffmpeg to do most of the encoding and updated [sub-cut.lua](https://github.com/kelciour/mpv-scripts/blob/master/sub-cut.lua) and I think it should work fine now.

**Comment by KingslyEn** [comment]
> @KingslyEn
> 
> > can I have your Email Adress
> 
> It's my nickname + @gmail.com, i.e. kelciour [at] gmail (dot) com.
> 
> > But windows Media player cant open this encoding file and just show black space with sound
> 
> Interesting. In the newer version I switched to mpv to do most of the encoding and the issue with Windows Media Player can be fixed by setting x264 profile level to 4.1, but for unknown reasons mpv mixes up video and audio streams and puts audio stream as the first stream in the file instead of video stream and some video editing software may not open correctly that file. For that reason, I reverted back to ffmpeg to do most of the encoding and updated [sub-cut.lua](https://github.com/kelciour/mpv-scripts/blob/master/sub-cut.lua) and I think it should work fine now.
Thank you again,I check it and its work,and play in windows mediaplayer,I must check in video edditing tools,But It must be Ok,thank you for your obligation,I`ll check it and say it to you if problem doesnt sove!

**Comment by KingslyEn** [comment]
It works correctly,I check it You can close this issue,
Thanks You a lot! ❤️

**Comment by kelciour** [comment]
No Problem. Glad to help.
