### ISSUE TITLE
NO files found or no progress!

### ISSUE THREAD

**Issue by raj6996** [kelciour/playphrase#21]
$ ./playphrase -i "D:\all\Season2" -o "D:\all\Extract\SRT" -v -s "all"
Number of clips: 0
   0% [>                         ] 0/0
Ok@DESKTOP-7J7A2A6 MINGW64 /d/playphrase-v1.2.9-win64
$
Nothing works from today, when I changed other files, it progress bar works, but no files created that folder.
videos files are mkv and vlc works fine!

**Comment by kelciour** [comment]
Try to run with `-d` to show grep results, i.e. `./playphrase -i "D:\all\Season2" -d "all"

If something is found, double-check that filenames are identical, e.g. file.mp4 and file.srt.

If nothing is found, try to regenerate txt files with `./playphrase -i "D:\all\Season2" _init_`
