### ISSUE TITLE
Desktop Apps

### ISSUE THREAD

**Issue by raj6996** [kelciour/playphrase#4]
Will you make desktop apps like videogrep(only works on MacOSX) for windows?
As visually editing (gui) works better than cli options. 
Hope you works on it.
thanks.

**Comment by kelciour** [comment]
I thought about making some kind of GUI with Electron and using marvellous [mpv.js](https://github.com/Kagami/mpv.js) plugin, but it's not gonna happen soon or it may never happen at all as I can't spend my free time on open source projects, at least not now.

**Comment by raj6996** [comment]
> 
> 
> I thought about making some kind of GUI with Electron and using marvellous [mpv.js](https://github.com/Kagami/mpv.js) plugin, but it's not gonna happen soon or it may never happen at all as I can't spend my free time on open source projects, at least not now.

https://github.com/antiboredom Never make an apps for windows, So I need to find alternative and luckily found your repo, but it works well but no cut option feature.
No problem, I need to wait for you whenever you have time!
Thanks.

**Comment by kelciour** [comment]
> no cut option feature

You can use playphrase with `sub-cut.lua` script from [mpv-scripts](https://github.com/kelciour/mpv-scripts) repository. If you've downloaded [playphrase-win32.zip](https://github.com/kelciour/playphrase/releases), then just download `sub-cut.lua` and put it into `playphrase\utils\mpv\scripts` folder. Default keybindings can be found at the beginning of `sub-cut.lua` file.

**Comment by raj6996** [comment]
Ok, How to use keybinding sub-cut.lua, I opened it in ATOM, saw usage, I pressed nothing happened?
> 
> --  Usage:
> --     w - set start timestamp
> --     e - set end timestamp
> --     ctrl+z - cut audio fragment
> --     ctrl+x - cut video fragment (with softsub subtitles)
> --     ctrl+c - cut video fragment with hardsub subtitles
> --     ctrl+w - replay from the start timestamp
> --     ctrl+e - replay the last n seconds until the end timestamp
> --     ctrl+r - reset timestamps

Nothing Happened?
kindly help me! thanks.

**Comment by kelciour** [comment]
Try to switch to english keyboard layout because the shortcuts may not work if the current active keyboard layout isn't set to english.

If this isn't the case, it probably means that lua script hadn't been loaded by mpv. Try to put `sub-cut.lua` in `%APPDATA%\mpv\scripts` folder, i.e. open `%APPDATA%` folder, create `mpv` folder, open it, create `scripts` folder and put `sub-cut.lua` there, i.e. the full path will be something like `C:\Users\Nickolay\AppData\Roaming\mpv\scripts\sub-cut.lua`.
