### ISSUE TITLE
Some Question

### ISSUE THREAD

**Issue by Mitijz** [kelciour/playphrase#6]
Hi,Thank you for your scripts
I need to add some features to the mpv(or Sub-Cut.lua) at the same time.
for example:

1: Show [FileName](https://github.com/yuukidach/mpv-scripts#show_filenamelua) and with a shortkey copy the name of the file.

2: When click click W for start time and E for End time,automatically times copy to clipboard!

3: Jump to time, somethings I can enter the times in this format `00:00:00.000` and then seek to it.

4: Search between current movie's subtitle. [Like This](https://github.com/kelciour/mpv-scripts/blob/master/sub-search.lua)!

I want to add them to sub-cut.lua and use them at the sametime.is it possible?

**Comment by kelciour** [comment]
Hi.

> 1: Show FileName and with a shortkey copy the name of the file.

As far as I know, this is platform specific (see https://github.com/mpv-player/mpv/issues/4695). For example, on Windows it can be done by using [nircmd](http://www.nirsoft.net/utils/nircmd.html). It should be added in PATH environment variable or at the same folder as `mpv.exe`. Here's a script - [copy-to-clipboard.lua](https://gist.github.com/kelciour/43ec30c34f4257c71d98e845dc7a9bb8).

> 2: When click click W for start time and E for End time,automatically times copy to clipboard!

I've updated `sub-cut.lua` using the same technique as before and uploaded it as a gist here - [link](https://gist.github.com/kelciour/bf76e2b9f8ae1b7c494b9b2f2b86e0f8).

> 3: Jump to time, somethings I can enter the times in this format `00:00:00.000` and then seek to it.

Maybe try [seek-to.lua](https://github.com/occivink/mpv-scripts#seek-tolua). There're no hotkeys by default and some hotkeys should be added to `input.conf` to make it work (it's in the same folder as `mpv.exe`).

	t script-message-to seek_to toggle-seeker

> 4: Search between current movie's subtitle. 

I've updated [sub-search.lua](https://github.com/kelciour/mpv-scripts/blob/master/sub-search.lua) and it should work with playphrase now. Just put it in the same folder as `sub-cut.lua` script.

I've attached zip archive with updated versions of `input.conf` and `*.lua` files - [mpv-scripts.zip](https://github.com/kelciour/playphrase/files/2609367/mpv-scripts.zip)

**Comment by Mitijz** [comment]
Thanks,All Done

**Comment by opa54321** [comment]
Привет, большое спасибо за скрипт! Но,не можешь подсказать как пользоваться командами для версии windows? 
Просто не понимаю, как их вводить, не изучал программирование и плохо в этом разбираюсь
-a, --audio — аудио
-v, --video — видео
-s, --video-sub — видео с субтитрами

**Comment by raj6996** [comment]
D:\Movies\English\playphrase>playphrase -i "D:\Movies\English\E_H_2020.mkv" -v -s "Grandpa"
None

**Comment by kelciour** [comment]
@raj6996 I created a new issue - https://github.com/kelciour/playphrase/issues/9
