### ISSUE TITLE
Use all system core

### ISSUE THREAD

**Issue by Mitijz** [kelciour/playphrase#7]
Hi dude, 
I set the encoding preset, I know it takes more time than ultrafast
But I don,t know FFMPEG use all system capability or not, So Is there a way to use FFMPEG use all system core for faster rendering in [[medium]] preset!

**Comment by kelciour** [comment]
> But I don,t know FFMPEG use all system capability or not,

The CPU usage can be seen either by using the built-in Windows Task Manager or [Process Explorer](https://docs.microsoft.com/ru-ru/sysinternals/downloads/process-explorer).

> So Is there a way to use FFMPEG use all system core for faster rendering in [[medium]] preset!

As far as I know, it's not necessary as it's already optimal, i.e. it's already using all system cores.

> Specifying `-threads 0` instructs the encoder to use all available cpu cores, which is the default. 

https://trac.ffmpeg.org/wiki/StreamingGuide#CPUusageFilesize

> FFmpeg should automatically choose the number of CPU threads available. However you may want to force the number of threads available by the parameter -threads <number>.

https://wiki.archlinux.org/index.php/FFmpeg#Encoding_examples

**Comment by Mitijz** [comment]
Thnaks 🙌
