### ISSUE TITLE
Привет, большое спасибо за скрипт! Но,не можешь подсказать как пользоваться командами для версии windows?

### ISSUE THREAD

**Issue by kelciour** [kelciour/playphrase#8]
Привет, большое спасибо за скрипт! Но,не можешь подсказать как пользоваться командами для версии windows? 
Просто не понимаю, как их вводить, не изучал программирование и плохо в этом разбираюсь
-a, --audio — аудио
-v, --video — видео
-s, --video-sub — видео с субтитрами

_Originally posted by @opa54321 in https://github.com/kelciour/playphrase/issues/6#issuecomment-505523477_

**Comment by kelciour** [comment]
@opa54321

Если просто поэкспериментировать, то можно открыть командую строку в папке с программой, например, введя в адресной строке проводника `cmd` и нажав Enter (https://alpinefile.ru/open-cmd-explorer-windows-10.html).

Либо можно попробовать открыть командную строку через Shift и правую клавишу мыши, но в Windows 10 командная строка заменена на PowerShell и я не уверен, что там все будет работать, но вроде как достаточно просто заменить PowerShell обратно на командную строку через "Параметры — Персонализация — Панель задач", отключив пункт "Заменить командную строку оболочкой Windows PowerShell" (https://remontka.pro/open-command-line-windows-10).

Например, можно ввести команду `playphrase`, чтобы убедиться, что все работает и получить список доступных ключей. После этого можно поэкспериментировать и вводить разные команды, например, `playphrase -i "H:\English Movies" "umbrella"`. Двойные кавычки можно опустить, если отсутствуют пробелы. Чтобы не вводить команду заново, можно нажать на клавиатуре стрелку вверх. Чтобы экспортировать видео, можно, например, ввести следующую команду `playphrase -i "H:\English Movies" -v "umbrella"`.

---

При желании можно добавить ключ через уже существующий батник, введя сначала ключ, потом двойную кавычку, потом при желании еще несколько ключей, потом через пробел еще одну кавычку, и потом уже слово для поиска, т.е. что-то типа:

    -v" "umbrella

или

    -v" -a "umbrella

---

Если постоянно, то проще всего создать копию батника и отредактировать в текстовом редакторе строчку #L14, добавив соответствующие команды, т.е. поменять
 
    playphrase.exe --input %media_dir% "!phrase!"

на

    playphrase.exe --input %media_dir% --video "!phrase!"

Когда-то записывал видео, как запустить под Windows 10, но там только редактирование батника - https://youtu.be/kEkXZY4LFCY?t=30

**Comment by opa54321** [comment]
Спасибо за ответ! Все получилось) И можно тогда узнать, на каком языке программирования был написан этот скрипт? Чтобы в дальнейшем постоянно не задавать вопросы, как включить ту функцию и т.д. А самому по экспериментировать, например с изменением времени вырезки аудио и т.п.

**Comment by kelciour** [comment]
Пожалуйста. Скрипт написан на Python 2.7.

**Comment by raj6996** [comment]
D:\Movies\English\playphrase>playphrase -i "D:\Movies\English\E_H_2020.mkv" -v -s "Grandpa"
None
